### ISSUE TITLE
Faltan algunas formas verbales

### ISSUE THREAD

**Issue by furstenheim** [JorgeDuenasLerin/diccionario-espanol-txt#1]
Hola Jorge,
Estaba mirando tu diccionario, pero faltan algunas palabras de formas verbales. Por ejemplo, "tocan". El problema es que la RAE no las muestra en comienzan con.

Gracias

**Comment by JorgeDuenasLerin** [comment]
Oh! es cierto. Gracias por el dato. Para procesar las conjugaciones tengo que meterme en cada palabra, lo he arreglado. Ahora mismo se está ejecutando pero tardará en procesar todo.

**Comment by JorgeDuenasLerin** [comment]
Ya se han descargado. Gracias por la incidencia!
