### ISSUE TITLE
Palabra que sobra.

### ISSUE THREAD

**Issue by Alejandro-GP** [JorgeDuenasLerin/diccionario-espanol-txt#12]
La palabra ababílla no es correcta. Está recortada quitándole el pronombre, pero en ese momento ya no llevaría tilde.

**Comment by JorgeDuenasLerin** [comment]
Tienes razón. Tengo que volver a ejecutar el script.

**Comment by JorgeDuenasLerin** [comment]
Volveré a ejecutar el script hoy.
