### ISSUE TITLE
Modo infinitivos

### ISSUE THREAD

**Issue by magancete** [JorgeDuenasLerin/diccionario-espanol-txt#4]
¿Es posible añadir una variable boolean para decidir si se quiere obtener la lista con conjugaciones o sin ellas?

**Comment by JorgeDuenasLerin** [comment]
Claro! Por defecto las descarga, si las quieres saltar usa --skip-conjugaciones. Necesitas argparse

**Comment by magancete** [comment]
Muchas gracias Jorge!

**Comment by JorgeDuenasLerin** [comment]
Voy a provechar a actualizar el listado de palabras con el server de la RAE. Voy a lanzar una ejecución sin las conjugaciones también.
