### ISSUE TITLE
Solucionar el problema al buscar js, app o doc

### ISSUE THREAD

**Issue by AIO1** [JorgeDuenasLerin/diccionario-espanol-txt#8]
En la URL para la consulta de la RAE se puede añadir un "/".
La URL para consultar algo que empiece por "app" sería por ejemplo:

https://dle.rae.es/app/?m=31

Y funcionaría sin problemas.
Lo que te estaba sucediendo es que app, docs y js parecen ser cosas reservadas que al no tener "/" en la consulta te dará un códgio de redireccionamiento HTTP.

Gracias a este cambio puedes elminar estas lineas del código:
![image](https://user-images.githubusercontent.com/17305493/206519556-878705c2-2f20-4acb-b4f1-86ed92e7696c.png)

**Comment by JorgeDuenasLerin** [comment]
Estoy revisando el script. Es cierto que de esa forma funciona.
