### ISSUE TITLE
Posibles palabras que faltan

### ISSUE THREAD

**Issue by AIO1** [JorgeDuenasLerin/diccionario-espanol-txt#9]
Al revisar el código y los resultados de la web, parece ser que hay algunos casos concretos donde sería conveniente añadir las letras también en mayusculas ya que devuelven distintos resultados.

![image](https://user-images.githubusercontent.com/17305493/206520203-fad8d176-ebb4-4a58-b94e-c0502bccd13d.png)

Un ejemplo sería intentar buscar "Alzheimer". No me da los mismos resultados si busco "alzhe" que "Alzhe".
![image](https://user-images.githubusercontent.com/17305493/206520388-ba3df1a8-2d9f-49b9-b85c-cf7ff10af704.png)
![image](https://user-images.githubusercontent.com/17305493/206520469-6ee3af3e-b09a-4ebd-af19-6800cb8e54b5.png)

**Comment by JorgeDuenasLerin** [comment]
Estoy revisando esto pero ahora mismo el servidor no devuelve datos con mayúsculas.
